version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
      time: "02:00"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
      time: "02:00"
