# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: c.rubler.net/blog
email: christoph.ruessler@mailbox.org
description: > # this means to ignore newlines until "baseurl:"
  About things I like and use: Linux, Ubuntu, KDE, Elixir, Phoenix, Elm, Ruby,
    Rails
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://c.rubler.net" # the base hostname & protocol for your site
twitter_username: cruessler
github_username:  cruessler

# Build settings
markdown: kramdown

show_drafts: false

exclude: ["vendor", "Gemfile*", "Session.vim"]

permalink: /:year/:month/:day/:title:output_ext

plugins:
  - jekyll-redirect-from
