on: [push]
name: build
jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        ruby: [ '3.3' ]

    name: Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v5

      - name: Setup Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Build
        run: |
          bundle install --jobs 4 --retry 3
          bin/jekyll build
