on: [push]
name: build
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        ruby: [ '2.6', '2.7' ]

    name: Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby ${{ matrix.ruby }}
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Build
        run: |
          gem install bundler:1.17.2
          bundle install --jobs 4 --retry 3
          bin/jekyll build
